#!/usr/bin/env sh
set -eu

target="${1:-.env.production}"

cat > "$target" <<EOF_ENV
NODE_ENV=production
APP_PUBLIC_URL=${APP_PUBLIC_URL}
ADMIN_PUBLIC_URL=${ADMIN_PUBLIC_URL}
API_PUBLIC_URL=${API_PUBLIC_URL}
NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL}
CUSTOMER_DOMAIN=${CUSTOMER_DOMAIN}
ADMIN_DOMAIN=${ADMIN_DOMAIN}
API_DOMAIN=${API_DOMAIN}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=${DATABASE_URL}
SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY}
TBANK_API_BASE_URL=${TBANK_API_BASE_URL}
TBANK_TERMINAL_KEY=${TBANK_TERMINAL_KEY}
TBANK_PASSWORD=${TBANK_PASSWORD}
TBANK_NOTIFICATION_URL=${TBANK_NOTIFICATION_URL}
TBANK_SUCCESS_URL=${TBANK_SUCCESS_URL}
TBANK_FAIL_URL=${TBANK_FAIL_URL}
TBANK_RECEIPT_TAXATION=${TBANK_RECEIPT_TAXATION}
TBANK_RECEIPT_TAX=${TBANK_RECEIPT_TAX}
TBANK_RECEIPT_PAYMENT_METHOD=${TBANK_RECEIPT_PAYMENT_METHOD}
TBANK_RECEIPT_PAYMENT_OBJECT=${TBANK_RECEIPT_PAYMENT_OBJECT}
PLATEGA_API_BASE_URL=${PLATEGA_API_BASE_URL}
PLATEGA_MERCHANT_ID=${PLATEGA_MERCHANT_ID}
PLATEGA_SECRET=${PLATEGA_SECRET}
EMAIL_PROVIDER=${EMAIL_PROVIDER}
EMAIL_FROM=${EMAIL_FROM}
EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
EMAIL_VERIFICATION_SECRET=${EMAIL_VERIFICATION_SECRET}
EMAIL_VERIFICATION_TTL_MIN=${EMAIL_VERIFICATION_TTL_MIN}
EMAIL_VERIFICATION_RESEND_COOLDOWN_SEC=${EMAIL_VERIFICATION_RESEND_COOLDOWN_SEC}
EMAIL_DOMAIN=${EMAIL_DOMAIN}
EMAIL_DKIM_SELECTOR=${EMAIL_DKIM_SELECTOR}
EMAIL_EXPECTED_SPF_INCLUDE=${EMAIL_EXPECTED_SPF_INCLUDE}
EMAIL_EXPECTED_MX=${EMAIL_EXPECTED_MX}
MARZBAN_BASE_URL=${MARZBAN_BASE_URL}
MARZBAN_USERNAME=${MARZBAN_USERNAME}
MARZBAN_PASSWORD=${MARZBAN_PASSWORD}
EXTERNAL_FALLBACK_URI_TEMPLATE=${EXTERNAL_FALLBACK_URI_TEMPLATE}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_BOT_SECRET=${TELEGRAM_BOT_SECRET}
TELEGRAM_ALERT_CHAT_ID=${TELEGRAM_ALERT_CHAT_ID}
EOF_ENV
