#!/usr/bin/env sh
set -eu

target="${1:-.env.production}"

cat > "$target" <<EOF_ENV
NODE_ENV=production
APP_PUBLIC_URL=${APP_PUBLIC_URL}
ADMIN_PUBLIC_URL=${ADMIN_PUBLIC_URL}
API_PUBLIC_URL=${API_PUBLIC_URL}
API_BASE_URL=${API_BASE_URL}
CUSTOMER_DOMAIN=${CUSTOMER_DOMAIN}
ADMIN_DOMAIN=${ADMIN_DOMAIN}
API_DOMAIN=${API_DOMAIN}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=${DATABASE_URL}
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY}
PLATEGA_API_BASE_URL=${PLATEGA_API_BASE_URL}
PLATEGA_MERCHANT_ID=${PLATEGA_MERCHANT_ID}
PLATEGA_SECRET=${PLATEGA_SECRET}
ROLLYPAY_API_BASE_URL=${ROLLYPAY_API_BASE_URL}
ROLLYPAY_MERCHANT_ID=${ROLLYPAY_MERCHANT_ID}
ROLLYPAY_SECRET=${ROLLYPAY_SECRET}
MARZBAN_BASE_URL=${MARZBAN_BASE_URL}
MARZBAN_USERNAME=${MARZBAN_USERNAME}
MARZBAN_PASSWORD=${MARZBAN_PASSWORD}
EXTERNAL_FALLBACK_URI_TEMPLATE=${EXTERNAL_FALLBACK_URI_TEMPLATE}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_BOT_SECRET=${TELEGRAM_BOT_SECRET}
TELEGRAM_ALERT_CHAT_ID=${TELEGRAM_ALERT_CHAT_ID}
EOF_ENV
